package gofront

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"reflect"
	"sort"
	"strings"
)

var errorType = reflect.TypeOf((*error)(nil)).Elem()

type boundMethod struct {
	object string
	method string
	fn     reflect.Value
}

type Binder struct {
	methods map[string]reflect.Value
	list    []boundMethod
}

func newBinder() *Binder {
	return &Binder{methods: map[string]reflect.Value{}}
}

func (b *Binder) bind(name string, v reflect.Value) {
	t := v.Type()
	for i := 0; i < t.NumMethod(); i++ {
		m := t.Method(i)
		if m.PkgPath != "" {
			continue
		}
		key := name + "." + m.Name
		b.methods[key] = v.Method(i)
		b.list = append(b.list, boundMethod{object: name, method: m.Name, fn: v.Method(i)})
	}
}

type callRequest struct {
	Method string            `json:"method"`
	Args   []json.RawMessage `json:"args"`
}

type callResponse struct {
	Result interface{} `json:"result,omitempty"`
	Error  string      `json:"error,omitempty"`
}

func (b *Binder) handleCall(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if r.Method != http.MethodPost {
		writeJSON(w, callResponse{Error: "method not allowed"})
		return
	}
	var req callRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, callResponse{Error: "bad request: " + err.Error()})
		return
	}
	result, err := b.invoke(req.Method, req.Args)
	if err != nil {
		writeJSON(w, callResponse{Error: err.Error()})
		return
	}
	writeJSON(w, callResponse{Result: result})
}

func (b *Binder) invoke(method string, args []json.RawMessage) (interface{}, error) {
	fn, ok := b.methods[method]
	if !ok {
		return nil, fmt.Errorf("unknown method %q", method)
	}
	ft := fn.Type()
	if len(args) != ft.NumIn() {
		return nil, fmt.Errorf("method %q expects %d args, got %d", method, ft.NumIn(), len(args))
	}
	in := make([]reflect.Value, ft.NumIn())
	for i := 0; i < ft.NumIn(); i++ {
		pv := reflect.New(ft.In(i))
		if err := json.Unmarshal(args[i], pv.Interface()); err != nil {
			return nil, fmt.Errorf("arg %d: %w", i, err)
		}
		in[i] = pv.Elem()
	}

	out := fn.Call(in)

	var results []interface{}
	for _, o := range out {
		if o.Type().Implements(errorType) {
			if !o.IsNil() {
				return nil, o.Interface().(error)
			}
			continue
		}
		results = append(results, o.Interface())
	}
	switch len(results) {
	case 0:
		return nil, nil
	case 1:
		return results[0], nil
	default:
		return results, nil
	}
}

func (b *Binder) generateJS() []byte {
	objects := map[string][]string{}
	for _, m := range b.list {
		objects[m.object] = append(objects[m.object], m.method)
	}
	names := make([]string, 0, len(objects))
	for n := range objects {
		names = append(names, n)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	buf.WriteString(jsRuntimeHeader)
	for _, obj := range names {
		fmt.Fprintf(&buf, "  window.gofront.%s = window.gofront.%s || {};\n", obj, obj)
		methods := objects[obj]
		sort.Strings(methods)
		for _, m := range methods {
			fmt.Fprintf(&buf,
				"  window.gofront.%s.%s = function() { return window.gofront.call(%q, Array.prototype.slice.call(arguments)); };\n",
				obj, m, obj+"."+m)
		}
	}
	buf.WriteString(jsRuntimeFooter)
	return buf.Bytes()
}

const jsRuntimeHeader = `// Code generated by gofront. DO NOT EDIT.
(function () {
  async function call(method, args) {
    const res = await fetch(location.origin + "/gofront/call", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ method: method, args: args }),
    });
    const data = await res.json();
    if (data.error) throw new Error(data.error);
    return data.result;
  }
  window.gofront = window.gofront || {};
  window.gofront.call = call;
`

const jsRuntimeFooter = `})();
`

func writeJSON(w http.ResponseWriter, v interface{}) {
	_ = json.NewEncoder(w).Encode(v)
}

// tsGen maps reflected Go types to TypeScript for gofront.d.ts.
// []byte becomes string (JSON base64). Named structs become interfaces.
type tsGen struct {
	defs       map[string]string
	order      []string
	inProgress map[string]bool
}

func newTSGen() *tsGen {
	return &tsGen{defs: map[string]string{}, inProgress: map[string]bool{}}
}

func (g *tsGen) typeOf(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Uintptr, reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return "string" // encoding/json encodes []byte as base64
		}
		return g.typeOf(t.Elem()) + "[]"
	case reflect.Array:
		return g.typeOf(t.Elem()) + "[]"
	case reflect.Map:
		return "{ [key: string]: " + g.typeOf(t.Elem()) + " }"
	case reflect.Ptr:
		return g.typeOf(t.Elem())
	case reflect.Struct:
		return g.structType(t)
	default:
		return "any"
	}
}

func (g *tsGen) structType(t reflect.Type) string {
	name := t.Name()
	if name == "" {
		return "{ " + g.structBody(t, " ") + " }"
	}
	if _, ok := g.defs[name]; ok {
		return name
	}
	if g.inProgress[name] {
		return name
	}
	g.inProgress[name] = true
	body := g.structBody(t, "\n  ")
	delete(g.inProgress, name)
	g.defs[name] = body
	g.order = append(g.order, name)
	return name
}

func (g *tsGen) structBody(t reflect.Type, sep string) string {
	var fields []string
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" {
			continue
		}
		name, opt, skip := jsonField(f)
		if skip {
			continue
		}
		q := ""
		if opt {
			q = "?"
		}
		fields = append(fields, name+q+": "+g.typeOf(f.Type)+";")
	}
	return strings.Join(fields, sep)
}

func jsonField(f reflect.StructField) (name string, optional, skip bool) {
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", false, true
	}
	parts := strings.Split(tag, ",")
	name = f.Name
	if parts[0] != "" {
		name = parts[0]
	}
	for _, p := range parts[1:] {
		if p == "omitempty" {
			optional = true
		}
	}
	return name, optional, false
}

func (g *tsGen) method(fn reflect.Value) (params, ret string) {
	ft := fn.Type()
	ps := make([]string, ft.NumIn())
	for i := 0; i < ft.NumIn(); i++ {
		ps[i] = fmt.Sprintf("a%d: %s", i, g.typeOf(ft.In(i)))
	}
	var outs []string
	for i := 0; i < ft.NumOut(); i++ {
		if ft.Out(i).Implements(errorType) {
			continue
		}
		outs = append(outs, g.typeOf(ft.Out(i)))
	}
	switch len(outs) {
	case 0:
		ret = "void"
	case 1:
		ret = outs[0]
	default:
		ret = "[" + strings.Join(outs, ", ") + "]"
	}
	return strings.Join(ps, ", "), "Promise<" + ret + ">"
}

func (b *Binder) generateTS() []byte {
	g := newTSGen()

	objects := map[string][]boundMethod{}
	for _, m := range b.list {
		objects[m.object] = append(objects[m.object], m)
	}
	objNames := make([]string, 0, len(objects))
	for n := range objects {
		objNames = append(objNames, n)
	}
	sort.Strings(objNames)

	var api bytes.Buffer
	api.WriteString("interface GoFront {\n")
	api.WriteString("  call(method: string, args: any[]): Promise<any>;\n")
	for _, obj := range objNames {
		ms := objects[obj]
		sort.Slice(ms, func(i, j int) bool { return ms[i].method < ms[j].method })
		fmt.Fprintf(&api, "  %s: {\n", obj)
		for _, m := range ms {
			params, ret := g.method(m.fn)
			fmt.Fprintf(&api, "    %s(%s): %s;\n", m.method, params, ret)
		}
		api.WriteString("  };\n")
	}
	api.WriteString("}\n")

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gofront. DO NOT EDIT.\nexport {};\n\n")
	for _, name := range g.order {
		fmt.Fprintf(&buf, "interface %s {\n  %s\n}\n\n", name, g.defs[name])
	}
	buf.Write(api.Bytes())
	buf.WriteString("\ndeclare global {\n  interface Window {\n    gofront: GoFront;\n  }\n}\n")
	return buf.Bytes()
}
